[package]
name = "logline-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
logline-api = { path = "../logline-api" }
serde.workspace = true
thiserror.workspace = true
toml = "0.9"
